# Proxy 기본 설정
proxy_redirect off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

# HTTP/1.1 Keep-Alive 설정
proxy_http_version 1.1;
proxy_set_header Connection "";

# Buffering 설정
proxy_buffering off;

# Cache 무효화 헤더
add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
add_header Pragma "no-cache";
